# Website settings
url: "https://www.hvdveer.nl"

# Internal nav
nav:
  main:
    writing: "/writing"
    speaking: "/speaking"
    projects: "/projects"
    photos: "profile-photos/profile_pic_hvdveer.jpg"
  writing:
    all: "/writing"
    popular: "/writing/popular"
    tags: "/writing/tags"
    rss: "/feed.xml"

# Bio settings
name: "Herman van der Veer"
description: "The home page of Herman van der Veer"
thumbnail_path: "/profile-photos/profile_pic_hvdveer.jpg"
bitcoin_address: "1G8qEUVUS8BBSwSWNM4EWR622vUpGtee66"
cloud_native_website: "https://github.com/aufbakanleitung/multi-docker"
website_repo_url: "https://github.com/aufbakanleitung/aufbakanleitung.github.io"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/hvdveer"
    label: "LinkedIn"
    icon: "linkedin-square"
  facebook:
    url: "https://www.facebook.com/Herman.van.der.Veer"
    label: "Facebook"
    icon: "facebook-square"
  github:
    url: "https://github.com/aufbakanleitung"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:hvdveer@gmail.com"
    label: "Email"
    value: "hvdveer@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'CET'
repository: aufbakanleitung.github.io

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
